# Handling Missing Values & Duplicates — Car Dataset

### 1. Load the car dataset

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('car.xlsx')
print(df.shape)
df.head()

(999, 5)

   User ID  Gender   Age  AnnualSalary  Purchased
0        1     0.0  32.0      100000.0          1
1        2     1.0  38.0       63500.0          0
2        3     0.0  20.0           NaN          0
3        4     1.0  48.0      119000.0          1
4        5     0.0  41.0      108500.0          1

### 2. Number of null values in each field

In [2]:
df.isnull().sum()

User ID           0
Gender           16
Age              93
AnnualSalary    118
Purchased         0
dtype: int64

### 3. Null values only in AnnualSalary

In [3]:
df['AnnualSalary'].isnull().sum()

np.int64(118)

### 4. Drop the rows having at least one null value in any field

In [4]:
print('Before:', df.shape)
df.dropna(how='any', inplace=True)
print('After :', df.shape)
df.isnull().sum()

Before: (999, 5)
After : (775, 5)

User ID         0
Gender          0
Age             0
AnnualSalary    0
Purchased       0
dtype: int64

### 5. Drop the rows having null values in all the fields

In [5]:
df = pd.read_excel('car.xlsx')   # reload original data (previous step already removed/filled the nulls)
print('Before:', df.shape)
df.dropna(how='all', inplace=True)
print('After :', df.shape)   # no row is completely empty, so nothing is dropped

Before: (999, 5)
After : (999, 5)

### 6. Drop the columns having at least one null value in any record

In [6]:
df = pd.read_excel('car.xlsx')   # reload original data (previous step already removed/filled the nulls)
df.dropna(axis=1, how='any', inplace=True)
print('Remaining columns:', list(df.columns))
df.head()

Remaining columns: ['User ID', 'Purchased']

   User ID  Purchased
0        1          1
1        2          0
2        3          0
3        4          1
4        5          1

### 7. Drop the columns having null values in all records

In [7]:
df = pd.read_excel('car.xlsx')   # reload original data (previous step already removed/filled the nulls)
df.dropna(axis=1, how='all', inplace=True)
print('Remaining columns:', list(df.columns))   # no column is completely empty

Remaining columns: ['User ID', 'Gender', 'Age', 'AnnualSalary', 'Purchased']

### 8. Create a copy of the dataset and replace the null values in AnnualSalary with 70000

In [8]:
df = pd.read_excel('car.xlsx')   # reload original data (previous step already removed/filled the nulls)
df_copy = df.copy()
df_copy['AnnualSalary'] = df_copy['AnnualSalary'].fillna(70000)
print('Nulls in AnnualSalary — copy    :', df_copy['AnnualSalary'].isnull().sum())
print('Nulls in AnnualSalary — original:', df['AnnualSalary'].isnull().sum())

Nulls in AnnualSalary — copy    : 0
Nulls in AnnualSalary — original: 118

### 9. Replace the null values in Age with 0

In [9]:
df['Age'] = df['Age'].fillna(0)
print('Nulls in Age:', df['Age'].isnull().sum())
print('Rows where Age = 0:', (df['Age'] == 0).sum())

Nulls in Age: 0
Rows where Age = 0: 93

### 10. Replace the null values in AnnualSalary with the mean

In [10]:
salary_mean = df['AnnualSalary'].mean()
print('Mean AnnualSalary:', round(salary_mean, 2))
df['AnnualSalary'] = df['AnnualSalary'].fillna(salary_mean)
print('Nulls in AnnualSalary:', df['AnnualSalary'].isnull().sum())

Mean AnnualSalary: 74641.88
Nulls in AnnualSalary: 0

### 11. Replace the null values in Age with the median

In [11]:
df = pd.read_excel('car.xlsx')   # reload: step 9 already set the missing Ages to 0
df['AnnualSalary'] = df['AnnualSalary'].fillna(salary_mean)   # keep the step-10 fill

age_median = df['Age'].median()
print('Median Age:', age_median)
df['Age'] = df['Age'].fillna(age_median)
print('Nulls in Age:', df['Age'].isnull().sum())

Median Age: 40.0
Nulls in Age: 0

### 12. Replace the null values in Gender with a suitable measure of central tendency
Gender is categorical (0/1), so mean and median are not meaningful — the **mode** is used.

In [12]:
gender_mode = df['Gender'].mode()[0]
print('Mode of Gender:', gender_mode)
df['Gender'] = df['Gender'].fillna(gender_mode)
print('Nulls in Gender:', df['Gender'].isnull().sum())

Mode of Gender: 0.0
Nulls in Gender: 0

### 13. Check for duplicates

In [13]:
print('Fully duplicated rows:', df.duplicated().sum())

# User ID is unique for every row, so also check the other columns
cols = ['Gender', 'Age', 'AnnualSalary', 'Purchased']
print('Duplicates ignoring User ID:', df.duplicated(subset=cols).sum())

Fully duplicated rows: 0
Duplicates ignoring User ID: 160

### 14. Remove the duplicate records

In [14]:
print('Before:', df.shape)
df.drop_duplicates(subset=cols, keep='first', inplace=True)
print('After :', df.shape)
print('Remaining duplicates:', df.duplicated(subset=cols).sum())

Before: (999, 5)
After : (839, 5)
Remaining duplicates: 0