In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

IF Statement

In [3]:
x=100
if x<50:
  print("Block 1")
  print("x is less than 50")
print("out of block1")

out of block1

In [5]:
x=45
if x<50:
  print("Block 1")
  print("x is less than 50")
  if x<25:
    print("Block 2")
    print("x is also less than 25")
print("out of block1")

Block 1
x is less than 50
out of block1

In [6]:
x=20
if x<50:
  print("Block 1")
  print("x is less than 50")
  if x<25:
    print("Block 2")
    print("x is also less than 25")
print("out of block1")

Block 1
x is less than 50
Block 2
x is also less than 25
out of block1

In [11]:
sales = 3750
target = 2000
if sales>=target:
  print("Sales target has been achieved!")
  print("Congratulations")
  if sales-target<=500:
    print("You have earned bonus 500")
  elif sales-target>500 and sales-target<=1000:
    print("You have earned bonus 1000")
  else:
    print("You have earned bonus 1500")
else:
  print("Sales target has not been approved")
  print("Kindly Improve!")

Sales target has been achieved!
Congratulations
You have earned bonus 1500

In [12]:
l1=list(range(0,5))
print(l1)

[0, 1, 2, 3, 4]

In [13]:
l1=list(range(0,10,2))
print(l1)

[0, 2, 4, 6, 8]

In [15]:
for i in range(0,5):
  print (i)

0
1
2
3
4

In [17]:
l2=[]
import numpy as np

for i in range(0,10,2):
  l2.append(int(np.square(i)))

print(l2)

[0, 4, 16, 36, 64]

In [18]:
for  i in range(0,5):
  for j in range(0,i):
    print(j,end="\t")
  print(end="\n")

0
0	1
0	1	2
0	1	2	3

In [20]:
import pandas as pd

In [24]:

df = pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer.xlsx')
df1 = pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer1.xlsx')
df2 = pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer2.xlsx')
df3 = pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer3.xlsx')
df4 = pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer4.xlsx')
df.head()
df1.head()
df2.head()
df3.head()
df4.head()

  Marital Status
0        Married
1         Single
2        Married
3        Married
4         Single

In [25]:
df1

,Customer,State,Customer Lifetime Value,Education,EmploymentStatus,Gender
0,BU79786,Washington,2763.519279,Bachelor,Employed,F
1,QZ44356,Arizona,6979.535903,Bachelor,Unemployed,F
2,AI49188,Nevada,12887.431650,Bachelor,Employed,F
3,WW63253,California,7645.861827,Bachelor,Unemployed,M
4,HB64268,Washington,2813.692575,Bachelor,Employed,M
...,...,...,...,...,...,...
80,ZU35962,California,8025.229358,College,Unemployed,F
81,VH85817,California,5780.182197,High School or Below,Employed,M
82,DT85712,California,4118.539113,Doctor,Employed,M
83,YJ88573,Nevada,2523.070150,Master,Employed,M
84,SQ19467,Oregon,6554.216396,College,Disabled,F

In [26]:
df

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2011-03-02 00:00:00,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,23405.987980,No,Basic,Bachelor,2011-10-02 00:00:00,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,3096.511217,Yes,Extended,College,2011-12-02 00:00:00,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,8163.890428,No,Extended,Bachelor,2011-06-02 00:00:00,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,7524.442436,No,Extended,College,2011-03-02 00:00:00,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [27]:
df2

   Customer  Number of Policies  Total Claim Amount
0   HW87852                   1          307.200000
1   HB20453                   5          982.399613
2   BN87372                   9          467.803638
3   YX23800                   2          350.400000
4   DZ87709                   6           29.034160
..      ...                 ...                 ...
74  AZ82578                   2          345.600000
75  XC67861                   4          321.600000
76  YC43143                   3           99.257608
77  EK59571                   1          504.000000
78  GD83998                   1          336.000000

[79 rows x 3 columns]

In [28]:
df3

,Customer,State,Customer Lifetime Value,Education,EmploymentStatus,Gender
0,EM66435,Oregon,2623.315430,Bachelor,Employed,F
1,QX45933,California,17840.195550,Bachelor,Unemployed,M
2,JI71369,California,5106.111827,College,Employed,F
3,JU93290,Arizona,17930.604510,College,Medical Leave,F
4,GU66096,Arizona,5457.342569,High School or Below,Employed,M
5,UC33108,California,6563.644143,Bachelor,Employed,M
6,LW93867,Oregon,4812.525221,College,Medical Leave,M
7,OU78470,Arizona,29328.041850,Master,Employed,F
8,XW90265,Arizona,5773.520711,Bachelor,Employed,F
9,HS67749,California,6847.118900,College,Employed,M
10,VZ51506,Arizona,3595.312860,High School or Below,Unemployed,F
11,UI64281,Nevada,22855.612090,Master,Medical Leave,F
12,AE98193,Washington,7859.414569,High School or Below,Unemployed,M
13,AZ74055,Oregon,4115.577437,High School or Below,Employed,M
14,XS76911,Arizona,5029.638777,High School or Below,Unemployed,F
15,AY40674,Washington,4821.418454,Bachelor,Employed,F
16,NA12740,Oregon,5004.310469,Master,Disabled,M
17,UA84837,Arizona,8630.053943,College,Employed,M
18,DJ51510,Arizona,9322.085120,High School or Below,Employed,F
19,VM58985,California,16727.560630,College,Unemployed,M
20,OH60605,Oregon,3652.532435,High School or Below,Employed,F
21,UO98052,Nevada,6158.601171,College,Unemployed,M
22,NC53424,California,4376.083958,Bachelor,Unemployed,M
23,LQ13873,Nevada,5569.456156,High School or Below,Employed,M
24,LA97014,Washington,2576.513006,Bachelor,Employed,M
25,NB79936,Washington,8346.983233,Bachelor,Employed,M
26,NT89061,Arizona,6323.923864,High School or Below,Employed,F
27,AF10970,Arizona,5973.143430,Bachelor,Employed,F
28,ZG48513,California,4706.676993,Bachelor,Unemployed,M
29,JQ59145,California,8093.410258,High School or Below,Unemployed,M
30,FE84989,Washington,5035.744643,College,Employed,M
31,JT52858,Oregon,9027.867218,Bachelor,Employed,F
32,MC62068,California,7288.884849,High School or Below,Employed,M
33,EU27538,Oregon,18042.479420,Master,Employed,M
34,RH42306,Arizona,4992.063043,Bachelor,Unemployed,F
35,US23612,Oregon,9102.267849,High School or Below,Disabled,F
36,WV76014,Arizona,2540.407726,Doctor,Employed,M
37,RK96223,California,12941.891930,College,Employed,M
38,MF82000,Washington,2365.348601,Bachelor,Unemployed,F
39,FM46980,Arizona,5720.765064,College,Employed,M
40,SY56792,Oregon,7035.534088,High School or Below,Unemployed,M
41,RF61565,California,2636.977730,College,Employed,M
42,IM94808,Nevada,5395.831967,Bachelor,Employed,M
43,VI14730,Oregon,8382.630118,High School or Below,Retired,M
44,YR34119,Washington,31161.745230,College,Employed,F
45,RR77985,Oregon,2887.742258,Bachelor,Unemployed,F
46,VC22097,Washington,8714.922135,College,Unemployed,F
47,WV17090,California,25585.727830,Bachelor,Unemployed,M
48,TM23514,Oregon,10272.608200,College,Employed,M
49,MQ68407,Oregon,4376.363592,Bachelor,Employed,F
50,GJ59592,California,5318.896640,Bachelor,Employed,F
51,FY56083,Oregon,4719.762191,Bachelor,Employed,M
52,UA94723,Oregon,4428.031583,High School or Below,Employed,F

In [29]:
df4

   Marital Status
0         Married
1          Single
2         Married
3         Married
4          Single
5         Married
6         Married
7          Single
8        Divorced
9         Married
10         Single
11        Married
12        Married
13        Married
14         Single
15        Married
16        Married
17        Married
18        Married
19        Married
20         Single
21       Divorced
22       Divorced
23         Single
24        Married
25        Married
26         Single
27        Married
28         Single
29        Married
30        Married
31        Married
32        Married
33        Married
34        Married
35        Married
36        Married
37        Married
38         Single
39       Divorced
40        Married
41         Single
42        Married
43        Married
44        Married
45        Married
46         Single
47         Single
48        Married
49        Married
50        Married
51       Divorced
52        Married
53        Married

In [30]:
print(df1.columns)
print(df2.columns)

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education',
       'EmploymentStatus', 'Gender'],
      dtype='object')
Index(['Customer', 'Number of Policies', 'Total Claim Amount'], dtype='object')

In [31]:
print(df1.shape)
print(df2.shape)

(85, 6)
(79, 3)

In [35]:
#Inner Merge
merged_inner = pd.merge(df1,df2,on='Customer',how='right')
print("---Inner Merge Result---")
print(len(df1))
print(len(df2))
print(len(merged_inner))
print(merged_inner.head())

---Inner Merge Result---
85
79
79
  Customer   State  Customer Lifetime Value             Education  \
0  HW87852  Oregon              2451.752695                Master
1  HB20453  Oregon              6781.270203              Bachelor
2  BN87372  Oregon              4974.801539              Bachelor
3  YX23800  Oregon              8591.604933              Bachelor
4  DZ87709  Oregon              5592.161392  High School or Below

  EmploymentStatus Gender  Number of Policies  Total Claim Amount
0    Medical Leave      M                   1          307.200000
1       Unemployed      M                   5          982.399613
2         Employed      M                   9          467.803638
3         Employed      M                   2          350.400000
4         Employed      F                   6           29.034160

In [36]:
df1

,Customer,State,Customer Lifetime Value,Education,EmploymentStatus,Gender
0,BU79786,Washington,2763.519279,Bachelor,Employed,F
1,QZ44356,Arizona,6979.535903,Bachelor,Unemployed,F
2,AI49188,Nevada,12887.431650,Bachelor,Employed,F
3,WW63253,California,7645.861827,Bachelor,Unemployed,M
4,HB64268,Washington,2813.692575,Bachelor,Employed,M
...,...,...,...,...,...,...
80,ZU35962,California,8025.229358,College,Unemployed,F
81,VH85817,California,5780.182197,High School or Below,Employed,M
82,DT85712,California,4118.539113,Doctor,Employed,M
83,YJ88573,Nevada,2523.070150,Master,Employed,M
84,SQ19467,Oregon,6554.216396,College,Disabled,F

Concatenating Dataset

In [37]:
df3=pd.read_excel('/content/gdrive/MyDrive/Dataset/Session 4/Insurance customer3.xlsx')

In [38]:
df3

,Customer,State,Customer Lifetime Value,Education,EmploymentStatus,Gender
0,EM66435,Oregon,2623.315430,Bachelor,Employed,F
1,QX45933,California,17840.195550,Bachelor,Unemployed,M
2,JI71369,California,5106.111827,College,Employed,F
3,JU93290,Arizona,17930.604510,College,Medical Leave,F
4,GU66096,Arizona,5457.342569,High School or Below,Employed,M
5,UC33108,California,6563.644143,Bachelor,Employed,M
6,LW93867,Oregon,4812.525221,College,Medical Leave,M
7,OU78470,Arizona,29328.041850,Master,Employed,F
8,XW90265,Arizona,5773.520711,Bachelor,Employed,F
9,HS67749,California,6847.118900,College,Employed,M
10,VZ51506,Arizona,3595.312860,High School or Below,Unemployed,F
11,UI64281,Nevada,22855.612090,Master,Medical Leave,F
12,AE98193,Washington,7859.414569,High School or Below,Unemployed,M
13,AZ74055,Oregon,4115.577437,High School or Below,Employed,M
14,XS76911,Arizona,5029.638777,High School or Below,Unemployed,F
15,AY40674,Washington,4821.418454,Bachelor,Employed,F
16,NA12740,Oregon,5004.310469,Master,Disabled,M
17,UA84837,Arizona,8630.053943,College,Employed,M
18,DJ51510,Arizona,9322.085120,High School or Below,Employed,F
19,VM58985,California,16727.560630,College,Unemployed,M
20,OH60605,Oregon,3652.532435,High School or Below,Employed,F
21,UO98052,Nevada,6158.601171,College,Unemployed,M
22,NC53424,California,4376.083958,Bachelor,Unemployed,M
23,LQ13873,Nevada,5569.456156,High School or Below,Employed,M
24,LA97014,Washington,2576.513006,Bachelor,Employed,M
25,NB79936,Washington,8346.983233,Bachelor,Employed,M
26,NT89061,Arizona,6323.923864,High School or Below,Employed,F
27,AF10970,Arizona,5973.143430,Bachelor,Employed,F
28,ZG48513,California,4706.676993,Bachelor,Unemployed,M
29,JQ59145,California,8093.410258,High School or Below,Unemployed,M
30,FE84989,Washington,5035.744643,College,Employed,M
31,JT52858,Oregon,9027.867218,Bachelor,Employed,F
32,MC62068,California,7288.884849,High School or Below,Employed,M
33,EU27538,Oregon,18042.479420,Master,Employed,M
34,RH42306,Arizona,4992.063043,Bachelor,Unemployed,F
35,US23612,Oregon,9102.267849,High School or Below,Disabled,F
36,WV76014,Arizona,2540.407726,Doctor,Employed,M
37,RK96223,California,12941.891930,College,Employed,M
38,MF82000,Washington,2365.348601,Bachelor,Unemployed,F
39,FM46980,Arizona,5720.765064,College,Employed,M
40,SY56792,Oregon,7035.534088,High School or Below,Unemployed,M
41,RF61565,California,2636.977730,College,Employed,M
42,IM94808,Nevada,5395.831967,Bachelor,Employed,M
43,VI14730,Oregon,8382.630118,High School or Below,Retired,M
44,YR34119,Washington,31161.745230,College,Employed,F
45,RR77985,Oregon,2887.742258,Bachelor,Unemployed,F
46,VC22097,Washington,8714.922135,College,Unemployed,F
47,WV17090,California,25585.727830,Bachelor,Unemployed,M
48,TM23514,Oregon,10272.608200,College,Employed,M
49,MQ68407,Oregon,4376.363592,Bachelor,Employed,F
50,GJ59592,California,5318.896640,Bachelor,Employed,F
51,FY56083,Oregon,4719.762191,Bachelor,Employed,M
52,UA94723,Oregon,4428.031583,High School or Below,Employed,F

In [39]:
print(df3.shape)

(53, 6)

In [40]:
vertical_concat = pd.concat([df1,df3],ignore_index=True)
print(vertical_concat.shape)

(138, 6)

In [41]:
print(vertical_concat.head())

  Customer       State  Customer Lifetime Value Education EmploymentStatus  \
0  BU79786  Washington              2763.519279  Bachelor         Employed
1  QZ44356     Arizona              6979.535903  Bachelor       Unemployed
2  AI49188      Nevada             12887.431650  Bachelor         Employed
3  WW63253  California              7645.861827  Bachelor       Unemployed
4  HB64268  Washington              2813.692575  Bachelor         Employed

  Gender
0      F
1      F
2      F
3      M
4      M

In [43]:
horizontal_concat=pd.concat([df3,df4],axis=1)
print(horizontal_concat.shape)

(54, 7)

In [45]:
print(horizontal_concat.head())

  Customer       State  Customer Lifetime Value             Education  \
0  EM66435      Oregon              2623.315430              Bachelor
1  QX45933  California             17840.195550              Bachelor
2  JI71369  California              5106.111827               College
3  JU93290     Arizona             17930.604510               College
4  GU66096     Arizona              5457.342569  High School or Below

  EmploymentStatus Gender Marital Status
0         Employed      F        Married
1       Unemployed      M         Single
2         Employed      F        Married
3    Medical Leave      F        Married
4         Employed      M         Single

In [50]:
print(df3.columns)
print(df4.columns)
print(df3.shape)
print(df4.shape)

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education',
       'EmploymentStatus', 'Gender'],
      dtype='object')
Index(['Marital Status'], dtype='object')
(53, 6)
(54, 1)